name: Release
run-name: Launch the next Release (${{ github.event.release.tags }}) by @${{ github.actor }}
on: 
    release:
        types: published
        tags: 'v*.*.*'
permissions:
  contents: read
  packages: write
jobs:
    build-docker:
        name: Build and Store Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: 'Start ${{ github.job }}'
              run: 'echo ${{ github.job }} started'
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Docker Setup Buildx
              uses: docker/setup-buildx-action@v3.6.1
            - name: Log in to the Container Registry
              uses: docker/login-action@v3.3.0
              with: 
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v6.7.0
              with:
                  context: ./nodeApp
                  push: true
                  tags: ghcr.io/ziffuge/overlay-twitch:latest,ghcr.io/ziffuge/overlay-twitch:${{ github.event.release.tags }}
            - name: Confirm ${{ github.job }}
              run: 'echo ${{ github.job }} terminated'
