name: Release
run-name: Launch the next Release by @${{ github.actor }}
on: 
    push:
        tags: '-v*.*.*'

jobs:
    build-docker:
        name: Build and Store Docker Image
        runs-on: windows-latest
        steps:
            - name: 'Confirm ${{ github.job }}'
              run: 'echo ${{ github.job }} started'
            - name: Checkout code
              uses: actions/checkout@v4
    build-plugin:
        name: Build and distribute plugin
        runs-on: windows-latest
        steps:
            - name: 'Confirm ${{ github.job }}'
              run: 'echo ${{ github.job }} started'
            - name: Checkout code
              uses: actions/checkout@v4
